"""Small built-in sound event taxonomy."""

from __future__ import annotations

from src.schemas import EventTaxonomyItem

TAXONOMY: dict[str, EventTaxonomyItem] = {
    "cup_hit": EventTaxonomyItem("cup_hit", "object", True, True, 350, (-4, 2), False, ["impact", "indoor"]),
    "cloth_rustle": EventTaxonomyItem("cloth_rustle", "movement", True, True, 500, (-10, -2), True, ["cloth", "indoor"]),
    "chair_move": EventTaxonomyItem("chair_move", "movement", True, True, 700, (-8, 0), False, ["chair", "indoor"]),
    "door_close_hard": EventTaxonomyItem("door_close_hard", "door", True, False, 700, (-4, 3), False, ["impact", "indoor"]),
    "door_knock": EventTaxonomyItem("door_knock", "door", True, False, 900, (-10, -2), False, ["door", "indoor", "knock"]),
    "door_open_soft": EventTaxonomyItem("door_open_soft", "door", True, True, 900, (-12, -4), False, ["door", "indoor", "soft"]),
    "footsteps_fast": EventTaxonomyItem("footsteps_fast", "footsteps", True, True, 1200, (-9, -1), True, ["movement"]),
    "footsteps_indoor": EventTaxonomyItem("footsteps_indoor", "footsteps", True, True, 1300, (-13, -4), True, ["movement", "indoor", "floor"]),
    "sigh": EventTaxonomyItem("sigh", "vocal_reaction", True, True, 800, (-12, -4), True, ["breath"]),
    "breath_heavy": EventTaxonomyItem("breath_heavy", "vocal_reaction", True, True, 900, (-14, -5), True, ["breath"]),
    "room_tone": EventTaxonomyItem("room_tone", "ambience", False, True, 12000, (-34, -20), True, ["room", "indoor", "ambience"]),
    "air_conditioner_hum": EventTaxonomyItem("air_conditioner_hum", "ambience", False, True, 10000, (-32, -18), True, ["indoor", "appliance", "hum"]),
    "fluorescent_light_hum": EventTaxonomyItem("fluorescent_light_hum", "ambience", False, True, 8000, (-34, -22), True, ["indoor", "electric", "hum"]),
    "paper_rustle": EventTaxonomyItem("paper_rustle", "object", True, True, 900, (-14, -5), True, ["paper", "indoor", "desk"]),
    "menu_page_turn": EventTaxonomyItem("menu_page_turn", "object", True, True, 900, (-16, -6), True, ["paper", "restaurant", "menu"]),
    "keyboard_typing": EventTaxonomyItem("keyboard_typing", "object", True, True, 1600, (-16, -7), True, ["keyboard", "indoor", "desk"]),
    "mouse_click": EventTaxonomyItem("mouse_click", "object", True, True, 500, (-18, -8), True, ["office", "computer", "click", "desk"]),
    "phone_vibrate": EventTaxonomyItem("phone_vibrate", "object", True, True, 1400, (-15, -5), False, ["phone", "indoor", "buzz"]),
    "light_switch_click": EventTaxonomyItem("light_switch_click", "object", True, True, 350, (-14, -4), False, ["switch", "indoor", "click"]),
    "bag_zip": EventTaxonomyItem("bag_zip", "object", True, True, 800, (-15, -6), True, ["bag", "zip", "indoor", "movement"]),
    "restaurant_murmur": EventTaxonomyItem("restaurant_murmur", "ambience", False, True, 12000, (-26, -12), True, ["restaurant", "crowd", "indoor"]),
    "cutlery_clink": EventTaxonomyItem("cutlery_clink", "object", True, True, 900, (-14, -4), True, ["restaurant", "cutlery", "table"]),
    "plate_set_down": EventTaxonomyItem("plate_set_down", "object", True, True, 800, (-12, -3), False, ["restaurant", "plate", "table"]),
    "glass_clink": EventTaxonomyItem("glass_clink", "object", True, True, 700, (-14, -4), False, ["restaurant", "glass", "table"]),
    "cup_set_down": EventTaxonomyItem("cup_set_down", "object", True, True, 700, (-13, -4), False, ["cup", "table", "indoor", "restaurant", "cafe"]),
    "pour_water": EventTaxonomyItem("pour_water", "object", True, True, 1800, (-18, -7), True, ["restaurant", "water", "table"]),
    "kitchen_clatter": EventTaxonomyItem("kitchen_clatter", "ambience", False, True, 5000, (-27, -13), True, ["restaurant", "kitchen", "indoor"]),
    "service_bell": EventTaxonomyItem("service_bell", "object", True, True, 900, (-16, -5), False, ["restaurant", "bell", "service"]),
    "rain_light": EventTaxonomyItem("rain_light", "ambience", False, True, 3000, (-24, -12), True, ["rain", "outdoor"]),
    "street_noise": EventTaxonomyItem("street_noise", "ambience", False, True, 12000, (-24, -10), True, ["street", "outdoor", "traffic"]),
    "crowd_murmur": EventTaxonomyItem("crowd_murmur", "ambience", False, True, 3000, (-22, -10), True, ["crowd"]),
    "car_passby_wet": EventTaxonomyItem("car_passby_wet", "vehicle", False, True, 4500, (-20, -8), True, ["street", "traffic", "wet"]),
    "car_passby_dry": EventTaxonomyItem("car_passby_dry", "vehicle", False, True, 4000, (-22, -9), True, ["street", "traffic", "dry", "daytime"]),
    "distant_siren": EventTaxonomyItem("distant_siren", "ambience", False, True, 4500, (-26, -13), True, ["street", "city", "siren", "outdoor"]),
    "horn_short": EventTaxonomyItem("horn_short", "vehicle", True, True, 1200, (-14, -4), False, ["street", "traffic", "horn"]),
    "bus_arrive": EventTaxonomyItem("bus_arrive", "vehicle", False, True, 5000, (-21, -9), True, ["street", "bus", "brake"]),
    "puddle_step": EventTaxonomyItem("puddle_step", "footsteps", True, True, 1300, (-10, -2), True, ["street", "water", "footsteps"]),
    "umbrella_rustle": EventTaxonomyItem("umbrella_rustle", "movement", True, True, 900, (-14, -5), True, ["rain", "umbrella", "cloth", "outdoor"]),
    "bicycle_bell": EventTaxonomyItem("bicycle_bell", "vehicle", True, True, 900, (-16, -6), False, ["street", "bicycle", "bell", "daytime"]),
    "bird_chirp": EventTaxonomyItem("bird_chirp", "ambience", False, True, 2200, (-28, -15), True, ["outdoor", "sunny", "daytime", "park"]),
    "crosswalk_beep": EventTaxonomyItem("crosswalk_beep", "signal", False, True, 1800, (-24, -12), True, ["street", "crosswalk", "daytime"]),
    "shop_door_chime": EventTaxonomyItem("shop_door_chime", "object", True, True, 1200, (-16, -5), False, ["street", "shop", "door", "daytime"]),
    "distant_construction": EventTaxonomyItem("distant_construction", "ambience", False, True, 6000, (-27, -13), True, ["street", "construction", "daytime"]),
    "wind_light": EventTaxonomyItem("wind_light", "ambience", False, True, 8000, (-28, -16), True, ["outdoor", "wind"]),
    "library_room_tone": EventTaxonomyItem("library_room_tone", "ambience", False, True, 10000, (-34, -22), True, ["library", "indoor", "quiet", "study"]),
    "book_page_turn": EventTaxonomyItem("book_page_turn", "object", True, True, 900, (-17, -7), True, ["library", "book", "paper", "study"]),
    "pen_write": EventTaxonomyItem("pen_write", "object", True, True, 1400, (-18, -9), True, ["library", "pen", "desk", "study"]),
    "espresso_machine": EventTaxonomyItem("espresso_machine", "appliance", True, True, 2600, (-20, -8), True, ["cafe", "coffee", "espresso", "machine"]),
    "coffee_grinder": EventTaxonomyItem("coffee_grinder", "appliance", True, True, 1800, (-20, -8), True, ["cafe", "coffee", "grinder", "machine"]),
    "milk_steam": EventTaxonomyItem("milk_steam", "appliance", True, True, 1600, (-22, -10), True, ["cafe", "coffee", "steam", "milk"]),
    "printer_whirr": EventTaxonomyItem("printer_whirr", "appliance", True, True, 2200, (-22, -10), True, ["office", "printer", "machine", "paper"]),
    "machine_hum": EventTaxonomyItem("machine_hum", "ambience", False, True, 10000, (-30, -17), True, ["industrial", "factory", "machine", "hum"]),
    "metal_clank": EventTaxonomyItem("metal_clank", "object", True, True, 1100, (-12, -3), False, ["industrial", "metal", "impact", "workshop"]),
    "hydraulic_hiss": EventTaxonomyItem("hydraulic_hiss", "ambience", True, True, 1600, (-20, -9), True, ["industrial", "hydraulic", "air", "machine"]),
}
